### PR TITLE
Merge pull request #11 from phil208-ethics-project/main

### PR DESCRIPTION
**Pull request by UD331**
I created the student table page. 

Not directly added the button as not sure where to put that but the page is this one- students
Can probably be accesses by https://phil208-ethics-project.github.io/#/students

### CODE REVIEW

**Review by SeanMcGuckin — COMMENTED** [review]
I don't see any changed files. Is this PR ready?

**Comment by UD331** [comment]
Hmm that's weird. I'll open another pull request you can check. Idk why it didn't show here. I'll upload commit again. My stuff is in the StudentBigTable folder.

**Comment by UD331** [comment]
Also added basic search and filtering options.

**Review by SeanMcGuckin — APPROVED** [review]
Most of this is beyond me, but for the parts I understand I think this looks fantastic.

**Pull request merged**
